const fs = require("fs");
let content = fs.readFileSync("src/components/editor/ExportModal.vue", "utf8");

// 1. Fix the HTML template inside doExportWeb
const oldHtmlChunk = "  const html = `<!DOCTYPE html>\\n  <html lang=\"en\">\\n  <head>\\n  <meta charset=\"UTF-8\">\\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\\n  <title>${exportName}</title>\\n  <link rel=\"stylesheet\" href=\"style.css\">\\n  </head>\\n  <body>\\n  <div class=\"lf-shell\">\\n  <div class=\"progress\" id=\"progress\"></div>\\n  <div class=\"lf-grid\"></div>\\n  <div class=\"lf-stage-shell\">\\n    <div class=\"presentation\" id=\"presentation\"></div>\\n  </div>\\n  <div class=\"dot-nav\" id=\"dot-nav\"></div>\\n  <nav class=\"nav\">\\n    <button class=\"nav-btn\" id=\"prev-btn\" type=\"button\">? Prev</button>\\n    <span class=\"nav-counter\" id=\"counter\">1 / ${slides.length}</span>\\n    <button class=\"nav-btn\" id=\"next-btn\" type=\"button\">Next ?</button>\\n  </nav>\\n  </div>\\n  ${dataScriptTag}\\n  ${runtimeScriptTag}\\n  </body>\\n  </html>`";

const newHtmlChunk = "  const bodyClass = mode === \"iframe\" ? \"is-iframe\" : mode === \"pdf\" ? \"is-pdf\" : \"\";\n  const isZip = mode !== \"pdf\";\n\n  const finalCss = isZip ? `<link rel=\"stylesheet\" href=\"style.css\">` : `<style>${css}</style>`;\n  const finalJs = isZip ? runtimeScriptTag : `<script>${js}</script>`;\n\n  const html = `<!DOCTYPE html>\\n  <html lang=\"en\">\\n  <head>\\n  <meta charset=\"UTF-8\">\\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\\n  <title>${exportName}</title>\\n  ${finalCss}\\n  </head>\\n  <body class=\"${bodyClass}\">\\n  <div class=\"lf-shell\">\\n  <div class=\"progress\" id=\"progress\"></div>\\n  <div class=\"lf-grid\"></div>\\n  <div class=\"lf-stage-shell\">\\n    <div class=\"presentation\" id=\"presentation\"></div>\\n  </div>\\n  <div class=\"dot-nav\" id=\"dot-nav\"></div>\\n  <nav class=\"nav\">\\n    <button class=\"nav-btn\" id=\"prev-btn\" type=\"button\">? Prev</button>\\n    <span class=\"nav-counter\" id=\"counter\">1 / ${slides.length}</span>\\n    <button class=\"nav-btn\" id=\"next-btn\" type=\"button\">Next ?</button>\\n  </nav>\\n  </div>\\n  ${dataScriptTag}\\n  ${finalJs}\\n  </body>\\n  </html>`;\n\n  if (mode === \"pdf\") {\n    const printWindow = window.open(\"\", \"_blank\");\n    printWindow.document.write(html);\n    printWindow.document.close();\n    exportStatus.value = \"success\";\n    setTimeout(() => exportStatus.value = \"\", 3000);\n    return;\n  }";
// wait, the arrows ? were stored as utf8? `? Prev` Let us just replace them with what is there

